version = 3

[transient_prompt]
  template = "% "
  foreground = "white"

[[blocks]]
  type = "prompt"
  alignment = "left" 

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }}'
    foreground = 'lightGreen'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    type = "git"
    style = "plain"
    template = " ({{ .HEAD }}{{ if or .Working.Changed .Staging.Changed }}*{{ end }})"
    foreground = "darkGray" 

    [blocks.segments.properties]
      branch_icon = ""
      commit_icon = "@"
      fetch_status = true

  [[blocks.segments]]
    type = "path"
    style = "plain"
    template = " {{ .Path }}"
    foreground = "lightBlue"
    
    [blocks.segments.properties]
      style = "full"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    template = "{{ if .Root }}#{{ else }}%{{ end }} "
    foreground = "white"

